// Mirror note: tests that need a signed Pro key are skipped here. The signing key
// lives only in the monorepo (keys/license-private.pem); run them there.
// Mirror note: tests that run a script from the monorepo's scripts/ directory are
// skipped here. That directory is not part of a server folder; run them in the monorepo.
// Mirror note: tests that read another server's source out of the monorepo are
// skipped here. A mirror holds one server and vendors a sibling's dist, never its
// src, so there is nothing to read; run them in the monorepo.
// Contract suite for statement-of-account. Generated shape, mechanical assertions only.
//
// Asserts the invariants of servers/statement-of-account/SPEC.md that a test can check
// without judgement: one version number across package.json, src/version.ts, serverInfo
// and all four registry manifests; the remotes rule (the mcpb manifest carries
// remotes.json, the second names carry none); JSON-RPC-only stdout; tool-description
// hygiene; the free/Pro tier switch; that the three sibling stores are read and never
// written; and that the record shapes this suite seeds still match the ones those servers
// declare. It never asserts a number a human chose; those live in test/unit.test.mjs.
import { test } from "node:test";
import assert from "node:assert/strict";
import { execFileSync } from "node:child_process";
import { readFileSync, statSync } from "node:fs";
import { join } from "node:path";
import { client, sandbox, cleanup, proKey, seed, storeDir, workedMonth, PERIOD, REPO } from "./_client.mjs";

const HERE = REPO;
const PRODUCT = "statement-of-account";
const MAX_DESCRIPTION = 220;
const HARD_MAX_DESCRIPTION = 1200;
const FILE_ARGS = ["path", "url", "out_path", "template_path"];
const IMPERATIVE = /^(Call this tool|Use this)\b/;

/**
 * Tools that already break the two description rules on the day this suite was written.
 * The suite is a ratchet: an existing entry is reported, a NEW one fails. Both lists are
 * defects; the fix is in src, not here.
 */
const OVER_LENGTH_BASELINE = [];
const NON_IMPERATIVE_BASELINE = [];

function open(t, opts = {}) {
  const box = sandbox();
  const c = client({ dataHome: box.dataHome, ...opts });
  t.after(() => { c.close(); cleanup(box.dir); });
  return { box, c };
}

test.skip("the version is one number: package.json, src/version.ts, serverInfo and every manifest agree", async (t) => {
  const pkg = JSON.parse(readFileSync(join(HERE, "package.json"), "utf8"));
  assert.equal(pkg.name, "@theluckystrike/mcp-statement-of-account");
  assert.ok(pkg.description.length < 100, `package description is ${pkg.description.length} chars`);
  const generated = readFileSync(join(HERE, "src", "version.ts"), "utf8");
  assert.match(generated, /GENERATED by scripts\/sync-versions\.mjs/, "version.ts must be generated, not hand written");
  assert.match(generated, new RegExp(`export const VERSION = "${pkg.version.replace(/\./g, "\\.")}";`),
    `src/version.ts does not carry ${pkg.version}; run node scripts/sync-versions.mjs`);

  const { c } = open(t);
  const info = await c.init();
  assert.equal(info.serverInfo.version, pkg.version, "serverInfo.version must equal the package version");
  assert.equal(info.serverInfo.name, "mcp-statement-of-account");

  for (const file of ["server.json", "server.mcpb.json", "server.variant.json", "server.dunning.json"]) {
    const j = JSON.parse(readFileSync(join(HERE, file), "utf8"));
    assert.equal(j.version, pkg.version, `${file} version`);
    for (const p of j.packages ?? []) {
      assert.equal(p.version, pkg.version, `${file} package entry version`);
      assert.equal(p.transport.type, "stdio", `${file} declares a transport this server does not speak`);
      if (p.registryType === "mcpb") {
        // "TBD" until the release job hashes the bundle; after that, a real sha256.
        assert.ok(p.fileSha256 === "TBD" || /^[0-9a-f]{64}$/.test(p.fileSha256),
          `${file} fileSha256 is neither TBD nor a sha256: ${p.fileSha256}`);
      }
    }
    if (file === "server.mcpb.json") {
      const remotes = JSON.parse(readFileSync(join(HERE, "remotes.json"), "utf8"));
      assert.deepEqual(j.remotes, remotes, `${file} remotes must equal remotes.json (hosted at /mcp/statement-of-account)`);
      assert.equal(remotes[0].url, "https://mcp.zovo.one/mcp/statement-of-account");
    } else {
      assert.equal(j.remotes, undefined, `${file} is a stdio-only name and must not advertise a remote`);
    }
    assert.ok((j.description ?? "").length < 100, `${file} description is ${(j.description ?? "").length} chars; the registry 422s at 100`);
    assert.ok(!/[,.]\.$|,$/.test(j.description), `${file} description ends in a machine truncation`);
  }
  // Three distinct registry names, so the second and third are second listings, not copies.
  const names = ["server.json", "server.variant.json", "server.dunning.json"]
    .map((f) => JSON.parse(readFileSync(join(HERE, f), "utf8")).name);
  assert.equal(new Set(names).size, 3, `registry names must differ: ${names.join(", ")}`);
  assert.deepEqual(names, [
    "io.github.theluckystrike/statement-of-account",
    "io.github.theluckystrike/aging",
    "io.github.theluckystrike/dunning",
  ]);

  // And sync-versions --check passes for the whole repo, so no sibling drifted either.
  execFileSync(process.execPath, [join(REPO, "scripts", "sync-versions.mjs"), "--check"], { encoding: "utf8" });
});

test("stdout carries JSON-RPC only across initialize, tools/list, a success and an error", async (t) => {
  const { box, c } = open(t);
  workedMonth(box.dataHome);
  await c.init();
  await c.tools();
  await c.call("statement_build", { client: "Acme Ltd", ...PERIOD });
  await c.call("statement_build", { client: "Wakanda Holdings", ...PERIOD });
  await new Promise((r) => setTimeout(r, 150));

  const lines = [...c.stdoutLines, c.tail].filter((l) => l.trim() !== "");
  assert.ok(lines.length >= 4, `expected at least 4 protocol lines, got ${lines.length}`);
  for (const line of lines) {
    let m;
    try { m = JSON.parse(line); } catch { assert.fail(`non-JSON on stdout: ${JSON.stringify(line.slice(0, 200))}`); }
    assert.equal(m.jsonrpc, "2.0", `stdout line is JSON but not JSON-RPC: ${line.slice(0, 200)}`);
  }
});

test("every tool description is non-empty, single-paragraph, and within the ceiling", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  assert.equal(tools.length, 8, "tool count changed; update servers/statement-of-account/SPEC.md");
  assert.deepEqual(tools.map((x) => x.name).sort(), [
    "dunning_text", "license_activate", "license_status", "statement_aging",
    "statement_build", "statement_pdf", "statement_text", "statements_report",
  ]);

  for (const tool of tools) {
    const d = tool.description ?? "";
    assert.ok(d.trim().length > 0, `${tool.name} has no description`);
    assert.equal(d, d.trim(), `${tool.name} description has leading or trailing whitespace`);
    assert.ok(d.length <= HARD_MAX_DESCRIPTION, `${tool.name} description is ${d.length} chars, over ${HARD_MAX_DESCRIPTION}`);
    assert.ok(!/[\u{1F300}-\u{1FAFF}\u{2600}-\u{27BF}]/u.test(d), `${tool.name} description carries an emoji`);
    assert.ok(!/[—]/.test(d), `${tool.name} description carries an em dash`);
  }

  const over = tools.filter((x) => (x.description ?? "").length > MAX_DESCRIPTION).map((x) => x.name).sort();
  const regressions = over.filter((n) => !OVER_LENGTH_BASELINE.includes(n));
  assert.deepEqual(regressions, [], `new tool descriptions over ${MAX_DESCRIPTION} chars`);
});

test("a tool that takes a file path opens with an imperative sentence", async (t) => {
  const { c } = open(t);
  await c.init();
  const tools = await c.tools();
  const fileTools = tools.filter((x) => Object.keys(x.inputSchema?.properties ?? {}).some((k) => FILE_ARGS.includes(k)));
  assert.deepEqual(fileTools.map((x) => x.name), ["statement_pdf"]);
  const offenders = fileTools.filter((x) => !IMPERATIVE.test(x.description ?? "")).map((x) => x.name).sort();
  assert.deepEqual(offenders.filter((n) => !NON_IMPERATIVE_BASELINE.includes(n)), []);
});

test.skip("license_status reports free with no key and pro with a signed key", async (t) => {
  const { c: free } = open(t);
  await free.init();
  const f = await free.call("license_status", {});
  assert.equal(f.isError, false, f.text);
  assert.match(f.text, /"tier":\s*"free"/, f.text.slice(0, 300));

  const key = proKey(PRODUCT);
  assert.match(key, /^MCPL1\./);
  const { c: pro } = open(t, { key });
  await pro.init();
  assert.match((await pro.call("license_status", {})).text, /"tier":\s*"pro"/);
});

test("the free tier is the documented one: aging free, five statements, PDF, level 3 and report Pro", async (t) => {
  const { box, c } = open(t);
  workedMonth(box.dataHome);
  await c.init();
  assert.equal((await c.call("statement_aging", {})).isError, false);
  assert.equal((await c.call("statement_build", { client: "Acme Ltd", ...PERIOD })).isError, false);
  assert.equal((await c.call("statement_text", { client: "Acme Ltd", ...PERIOD })).isError, false);
  assert.equal((await c.call("dunning_text", { client: "Acme Ltd", level: 1, as_of: "2026-06-30" })).isError, false);
  for (const [tool, args] of [
    ["statement_pdf", { client: "Acme Ltd", ...PERIOD }],
    ["dunning_text", { client: "Acme Ltd", level: 3, as_of: "2026-06-30" }],
    ["statements_report", {}],
  ]) {
    const r = await c.call(tool, args);
    assert.equal(r.isError, true, `${tool} answered on the free tier`);
    assert.match(r.text, /Pro is a one-time \$\d+ for this server/, tool);
    assert.match(r.text, /license_activate/, tool);
  }
});

test("the resource and the prompt are registered and answer", async (t) => {
  const { box, c } = open(t);
  workedMonth(box.dataHome);
  await c.init();
  const res = (await c.send("resources/read", { uri: "statement://sources" })).result;
  const body = JSON.parse(res.contents[0].text);
  assert.deepEqual(body.reads.map((x) => x.store), ["invoice", "billing-docs credit notes", "deposits"]);
  assert.deepEqual(body.clients, ["Acme Ltd", "Beta GmbH"]);
  assert.equal(body.writes.length, 1);
  assert.equal(body.writes[0].store, "statement-of-account");
  const prompts = (await c.send("prompts/list", {})).result.prompts;
  assert.deepEqual(prompts.map((p) => p.name), ["chase_overdue"]);
});

test.skip("no sibling store is ever written, on any tool, including the PDF path", async (t) => {
  const { box, c } = open(t, { key: proKey() });
  workedMonth(box.dataHome);
  await c.init();
  const watched = [
    ["invoice", "invoices.json"], ["invoice", "clients.json"],
    ["billing-docs", "credit-notes.json"], ["deposits", "deposits.json"],
    ["profile", "business.json"],
  ];
  const before = watched.map(([s, f]) => {
    const p = join(storeDir(box.dataHome, s), f);
    return [p, readFileSync(p, "utf8"), statSync(p).mtimeMs];
  });
  await c.call("statement_build", { client: "Acme Ltd", ...PERIOD });
  await c.call("statement_text", { client: "Acme Ltd", ...PERIOD });
  await c.call("statement_pdf", { client: "Acme Ltd", ...PERIOD, out_path: `${box.dir}/x.pdf` });
  await c.call("statement_aging", {});
  await c.call("dunning_text", { client: "Acme Ltd", level: 3, as_of: "2026-06-30" });
  await c.call("statements_report", {});
  for (const [p, text, mtime] of before) {
    assert.equal(readFileSync(p, "utf8"), text, `${p} was rewritten`);
    assert.equal(statSync(p).mtimeMs, mtime, `${p} was touched`);
  }
});

test.skip("the seeded record shapes still match what the sibling servers declare", async (t) => {
  // If a sibling renames a field, this suite's seeds would silently stop reaching the
  // code that reads them, and every figure would quietly become zero. These are the
  // fields this server actually depends on, checked against the sibling's own source.
  const need = {
    "invoice/src/store.ts": ["number", "client_id", "issue_date", "due_date", "currency", "total_minor", "paid_minor", "paid_date", "payments"],
    "billing-docs/src/store.ts": ["invoice_number", "issue_date", "currency", "total_minor", "reason"],
    "deposits/src/store.ts": ["amount_minor", "currency", "received_date", "applications", "refunds"],
  };
  for (const [file, fields] of Object.entries(need)) {
    const src = readFileSync(join(REPO, "servers", file), "utf8");
    for (const f of fields) {
      assert.match(src, new RegExp(`^\\s*${f}[?]?:`, "m"), `${file} no longer declares ${f}`);
    }
  }
  // And DepositApplication still names the invoice it paid, which is the only join
  // between the deposit book and the invoice ledger.
  const dep = readFileSync(join(REPO, "servers", "deposits", "src", "store.ts"), "utf8");
  assert.match(dep, /interface DepositApplication \{[^}]*invoice_number: string/s);
});

test("src holds no network call and no stdout write", async () => {
  // grep exits 1 on no match, which is the passing case here.
  let raw = "";
  try {
    raw = execFileSync("grep", ["-rEn", "fetch\\(|https?://|node:http|node:net|node:dns|console\\.", join(HERE, "src")], { encoding: "utf8" });
  } catch (e) {
    if (e.status !== 1) throw e;
  }
  const out = raw.trim().split("\n").filter(Boolean);
  const offending = out.filter((l) => !/mcp\.zovo\.one/.test(l));
  assert.deepEqual(offending, [], `network or stdout in src:\n${offending.join("\n")}`);
});
